<div class = 'megacontainer'>
    <ul id="megamenu">
        <?php
        $MegaItems = $this->getMegaItem();
        foreach ($MegaItems as $Item){
            switch($Item['type']){
                case 1:
                    echo "<li category_id=".$Item['value']. ">";
                    echo $this->createCategoryLink($Item['title'],$Item['value']);
                    echo "</li>";
                    break;

                case 2:
                    echo "<li>";
                    echo $this->createCustomLink($Item['title'],$Item['value']);
                    echo "</li>";
                    break;
                case 3:
                    echo "<li>";
                    echo $this->createBlockLink($Item['title'],$Item['value']);
                    echo "</li>";
                    break;
            }
        } // end foreach
        ?>
    </ul>
</div>

<?php
/**
 * Auto hightlight active (current) category
 */
$PathIds = Mage::getModel('catalog/layer')->getCurrentCategory()->getPathIds();
?>
<script>
    $(function(){

        <?php foreach ($PathIds as $id) : ?>
             $('li[category_id=<?php echo $id; ?>]').addClass('active-category');
        <?php endforeach; ?>
        /**
         * for Home
          */
        <?php $HandleArray = Mage::app()->getLayout()->getUpdate()->getHandles();
            if(in_array('cms_index_index',$HandleArray)){
            ?>
                $('#megamenu >li:first-child').addClass('active-category');
            <?php
            }
         ?>
    });
</script>


