<div class = 'megacontainer'>
    <ul id="megamenu">
        <?php
        $MegaItems = $this->getMegaItem();
        foreach ($MegaItems as $Item){
            switch($Item['type']){
                case 1:
//                echo 'category root id =';
                    echo "<li>";
                    echo $this->createCategoryLink($Item['title'],$Item['value']);
                    echo "</li>";
                    break;

                case 2:
                    echo "<li>";
                    echo $this->createCustomLink($Item['title'],$Item['value']);
                    echo "</li>";
                    break;
                case 3:
                    echo "<li>";
                    echo $this->createBlockLink($Item['title'],$Item['value']);
                    echo "</li>";
                    break;
            }
        } // end foreach
        ?>
    </ul>
</div>
