<style>

    .red-slide {
        background: #ca4040;
    }
    .blue-slide {
        background: #4390ee;
    }
    .orange-slide {
        background: #ff8604;
    }

</style>


<div class="swiper-container featured">
    <div class="swiper-wrapper">
        <div class="swiper-slide blue-slide">
            <div class="title">Vertical Mode</div>
            <p>Swipe to the Top or to the Bottom</p>
        </div>
        <div class="swiper-slide red-slide">
            <div class="title">Slide 2</div>
            <p>Keep swiping</p>
        </div>
        <div class="swiper-slide orange-slide">
            <div class="title">Slide 3</div>
            <p>The last one</p>
        </div>
    </div>
    <div class="pagination"></div>
</div>

<script>
//    var mySwiper = new Swiper('.featured-swiper-container',{
//        pagination: '.pagination',
//        paginationClickable: true,
//        slideClass: 'featured-swiper-slide',
//        slideActiveClass: 'featured-swiper-slide-active',
//        slideVisibleClass: 'featured-swiper-slide-visible',
//        slideDuplicateClass: 'featured-swiper-slide-duplicate',
//        wrapperClass: 'featured-swiper-wrapper'
//        mode: 'horizontal'
//    })
window.onload = function() {
    var mySwiper = new Swiper('.featured',{
        mode:'horizontal'
//        loop:true
//        autoplay: 1000
    });
}
</script>